source 'https://rubygems.org'

gem 'discordrb', git: 'https://github.com/shardlab/discordrb.git'
gem 'sequel'
gem 'sqlite3'
gem 'rufus-scheduler'
gem 'twelvedata_ruby'
gem 'httparty'
gem 'nokogiri'
gem 'faraday'
